spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        type: com.zaxxer.hikari.HikariDataSource
        hikari:
            minimum-idle: 5
            maximum-pool-size: 15
            connection-timeout: 3000000
            idle-timeout: 600000000
            max-lifetime: 21331231232
        url: ${datasource_url}
        username: ${datasource_username}
        password: ${datasource_password}
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: none
